name: Validate & Deploy
on:
  #schedule:
  #  - cron: '30 5 * * *'
  push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
    inputs:
      target:
        description: 'Version to deploy'
        required: true
        default: 'latest'
        type: string

jobs: 
  validate:
    runs-on: ubuntu-latest
    defaults:
          run:
            shell: cmd    
    strategy:
      matrix:
        database: [Postgres, Postgres]
    steps:
        - uses: actions/checkout@v3
      
        - name: Flyway Clean
          run: C:/Program Files/Red Gate/Flyway Desktop/flyway> 
                  -url=jdbc:postgresql://localhost:5432/postgres;encrypt=false;databaseName=${{ matrix.database }}_Build; 
                  -user=${{secrets.DB_USERNAME}} 
                  -password=${{secrets.DB_PASSWORD}}  
                  -licenseKey=${{ secrets.FLYWAY_LICENSE_KEY }}
                  -cleanDisabled="false"
          working-directory: ./${{ matrix.database }}/
      
        - name: Flyway Migrate
          run: C:/Program Files/Red Gate/Flyway Desktop/flyway> 
                  -url=jdbc:postgresql://localhost:5432/postgres;encrypt=false;databaseName=${{ matrix.database }}_Build; 
                  -user=${{secrets.DB_USERNAME}} 
                  -password=${{secrets.DB_PASSWORD}}   
                  -licenseKey=${{ secrets.FLYWAY_LICENSE_KEY }}
          working-directory: ./${{ matrix.database }}/
              
                  #-target=${{ github.event.inputs.target }}
          